"""durable shared-state tables (DS-4)

Created by hand, not with --autogenerate.

WHY EXPLICIT. Every constraint here carries tenant semantics: the composite
uniques are what stop two tenants colliding on a session id or an idempotency
key, and the composite indexes are what make a tenant-scoped read the cheap
query. An autogenerated revision can produce a correct-looking table with a
plain `unique(session_id)`, and nothing in CI would notice until two tenants
shared a session id in production.

This is revision 3 on the EXISTING history, not a fresh "001". The auth schema
already had two revisions, and pretending the database had no prior schema is the
kind of lie that makes an import later produce a duplicate-object error.

WHAT IT DOES NOT ESTABLISH. No migration here has been applied to a real Azure
database. LIVE_AZURE_MIGRATION_HISTORY = UNVERIFIED.

Revision ID: 3_durable_shared_state
Revises: 2_employee_reset
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "3_durable_shared_state"
down_revision = "2_employee_reset"
branch_labels = None
depends_on = None

# A Column TYPE, not a Column: `nullable` belongs to sa.Column, and passing it
# here raises `TypeError: String.__init__() got an unexpected keyword argument
# 'nullable'` at import time — inside revision loading, so the failure surfaces
# as an opaque traceback from `alembic upgrade` rather than as a schema error.
TENANT = sa.String(length=255)


def _uuid():
    return postgresql.UUID(as_uuid=True)


def _ts():
    return sa.DateTime(timezone=True)


def upgrade() -> None:
    op.create_table(
        "conversations",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("tenant_id", TENANT),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("created_at", _ts(), nullable=False),
        sa.Column("updated_at", _ts(), nullable=False),
        # Tenant-scoped uniqueness: two tenants may legitimately share a
        # session_id, and a global unique index would leak existence.
        sa.UniqueConstraint(
            "tenant_id", "session_id", name="uq_conversations_tenant_session"
        ),
    )
    op.create_index("ix_conversations_tenant_id", "conversations", ["tenant_id"])

    op.create_table(
        "conversation_messages",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("tenant_id", TENANT),
        sa.Column(
            "conversation_id",
            _uuid(),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", _ts(), nullable=False),
        sa.UniqueConstraint(
            "conversation_id", "seq", name="uq_messages_conversation_seq"
        ),
    )
    op.create_index(
        "ix_messages_tenant_conversation",
        "conversation_messages",
        ["tenant_id", "conversation_id"],
    )

    op.create_table(
        "agent_runs",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("tenant_id", TENANT),
        sa.Column(
            "conversation_id",
            _uuid(),
            sa.ForeignKey("conversations.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status", sa.String(length=32), nullable=False, server_default="running"
        ),
        sa.Column("started_at", _ts(), nullable=False),
        sa.Column("ended_at", _ts(), nullable=True),
        sa.UniqueConstraint(
            "tenant_id", "thread_id", name="uq_agent_runs_tenant_thread"
        ),
    )
    op.create_index(
        "ix_agent_runs_tenant_status", "agent_runs", ["tenant_id", "status"]
    )

    op.create_table(
        "agent_checkpoints",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("tenant_id", TENANT),
        sa.Column(
            "agent_run_id",
            _uuid(),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", _ts(), nullable=False),
        sa.UniqueConstraint("agent_run_id", "seq", name="uq_checkpoints_run_seq"),
    )
    op.create_index(
        "ix_checkpoints_tenant_run",
        "agent_checkpoints",
        ["tenant_id", "agent_run_id"],
    )

    op.create_table(
        "approval_requests",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("tenant_id", TENANT),
        sa.Column(
            "agent_run_id",
            _uuid(),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "conversation_id",
            _uuid(),
            sa.ForeignKey("conversations.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("tool", sa.String(length=128), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=32), nullable=False, server_default="pending"
        ),
        sa.Column(
            "proposal",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("created_at", _ts(), nullable=False),
        sa.Column("decided_at", _ts(), nullable=True),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
    )
    op.create_index(
        "ix_approvals_tenant_status", "approval_requests", ["tenant_id", "status"]
    )
    op.create_index(
        "ix_approvals_tenant_created", "approval_requests", ["tenant_id", "created_at"]
    )

    op.create_table(
        "idempotency_records",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("tenant_id", TENANT),
        sa.Column("operation_type", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            server_default="in_progress",
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", _ts(), nullable=False),
        sa.Column("completed_at", _ts(), nullable=True),
        # The correctness mechanism for duplicate side effects: two concurrent
        # claimants race on INSERT and exactly one wins.
        sa.UniqueConstraint(
            "tenant_id",
            "operation_type",
            "idempotency_key",
            name="uq_idempotency_scope_key",
        ),
    )

    op.create_table(
        "audit_events",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("tenant_id", TENANT),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("created_at", _ts(), nullable=False),
    )
    op.create_index(
        "ix_audit_tenant_created", "audit_events", ["tenant_id", "created_at"]
    )

    op.create_table(
        "job_records",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("tenant_id", TENANT),
        sa.Column("job_type", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=32), nullable=False, server_default="queued"
        ),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", _ts(), nullable=False),
        sa.Column("updated_at", _ts(), nullable=False),
        # A redelivered Event Grid notification collapses onto the existing row
        # instead of causing a second ingestion of the same document.
        sa.UniqueConstraint(
            "tenant_id", "job_type", "document_id", name="uq_jobs_tenant_type_document"
        ),
    )
    op.create_index("ix_jobs_tenant_status", "job_records", ["tenant_id", "status"])


def downgrade() -> None:
    """Reverse order so foreign keys never dangle mid-teardown.

    Alembic runs downgrade inside a transaction on PostgreSQL, so a wrong order
    would fail on the FK rather than corrupt — but failing on the FK is not a
    useful error message, and a downgrade that cannot complete leaves the database
    unusable.
    """
    op.drop_table("job_records")
    op.drop_table("audit_events")
    op.drop_table("idempotency_records")
    op.drop_table("approval_requests")
    op.drop_table("agent_checkpoints")
    op.drop_table("agent_runs")
    op.drop_table("conversation_messages")
    op.drop_table("conversations")
