from __future__ import with_statement
from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context
import os
import sys

# Add the src directory to the path so we can import maia modules
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "src"))

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# URL PRECEDENCE: MAIA_DATABASE_URL (env) wins over `sqlalchemy.url` in
# alembic.ini.
#
# WHY. The committed default is `sqlite:///./maia_auth.db`, which is correct for
# the legacy auth schema and useless for the durable PostgreSQL state. Rather than
# editing the ini — which would silently repoint every existing invocation — the
# durable lane supplies its DSN here. A credential in a committed ini is a
# credential in the repository, so the DSN is never written to a file.
#
# `%` is doubled because Alembic's ConfigParser uses interpolation: a password
# containing `%` would otherwise raise at read time with a message that looks
# like a config bug rather than a DSN escaping problem.
_dsn = os.environ.get("MAIA_DATABASE_URL")
if _dsn:
    config.set_main_option("sqlalchemy.url", _dsn.replace("%", "%%"))

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Add your model's MetaData object here
# for 'autogenerate' support
# from myapp import mymodel
# target_metadata = mymodel.Base.metadata
from maia.models import Base

# The durable shared-state schema (DS-2) lives in a SEPARATE Base on purpose —
# see maia/durable_models.py for why it must not share metadata with auth.
#
# Autogenerate is fed the UNION so a single `alembic revision --autogenerate`
# sees both schemas. That union is only ever used for generating a diff; the
# migration files themselves are explicit `op.create_table` calls, because an
# autogenerated revision that silently drops or renames a tenant-scoped
# constraint is exactly the kind of change that should never be auto-merged.
#
# The legacy auth schema (models.Base) is still created by `create_all()` at API
# startup against SQLite. That is a separate open defect, not something this
# file pretends to have solved.
from maia.durable_models import DurableBase
from sqlalchemy import MetaData

# `Table.to_metadata` copies the table's constraints AND indexes, so the composite
# uniques and tenant indexes survive into the union. An earlier version tried to
# copy each constraint individually and died on
# `AttributeError: 'PrimaryKeyConstraint' object has no attribute 'to_metadata'`
# — which is worth recording because that failure happened inside a migration
# that a naive `exit 0` check would have reported as a pass.
target_metadata = MetaData()
for _base in (Base, DurableBase):
    for _table in _base.metadata.tables.values():
        _table.to_metadata(target_metadata, schema=_table.schema)

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI.  However, empty
    database.url values will raise an error.  Just a
    basic configuration here.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    # this creates the Engine using SQLAlchemy's
    # passthrough connection.
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
